/*
-- Query: SELECT * FROM budgetiq.country
LIMIT 0, 1000

-- Date: 2025-06-23 23:46
*/
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AD','Andorra','Andorra la Vella','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AE','United Arab Emirates','Abu Dhabi','AED','Dirham');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AF','Afghanistan','Kabul','AFN','Afghani');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AG','Antigua and Barbuda','St. John\'s','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AI','Anguilla','The Valley','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AL','Albania','Tirana','ALL','Lek');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AM','Armenia','Yerevan','AMD','Dram');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AN','Netherlands Antilles','Willemstad','ANG','Guilder');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AO','Angola','Luanda','AOA','Kwanza');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AQ','Antarctica','','','');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AR','Argentina','Buenos Aires','ARS','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AS','American Samoa','Pago Pago','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AT','Austria','Vienna','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AU','Australia','Canberra','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AW','Aruba','Oranjestad','AWG','Guilder');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AX','Aland Islands','Mariehamn','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('AZ','Azerbaijan','Baku','AZN','Manat');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BA','Bosnia and Herzegovina','Sarajevo','BAM','Marka');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BB','Barbados','Bridgetown','BBD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BD','Bangladesh','Dhaka','BDT','Taka');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BE','Belgium','Brussels','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BF','Burkina Faso','Ouagadougou','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BG','Bulgaria','Sofia','BGN','Lev');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BH','Bahrain','Manama','BHD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BI','Burundi','Bujumbura','BIF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BJ','Benin','Porto-Novo','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BL','Saint Barthelemy','Gustavia','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BM','Bermuda','Hamilton','BMD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BN','Brunei','Bandar Seri Begawan','BND','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BO','Bolivia','Sucre','BOB','Boliviano');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BQ','Bonaire, Saint Eustatius and Saba ','','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BR','Brazil','Brasilia','BRL','Real');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BS','Bahamas','Nassau','BSD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BT','Bhutan','Thimphu','BTN','Ngultrum');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BV','Bouvet Island','','NOK','Krone');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BW','Botswana','Gaborone','BWP','Pula');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BY','Belarus','Minsk','BYR','Ruble');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('BZ','Belize','Belmopan','BZD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CA','Canada','Ottawa','CAD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CC','Cocos Islands','West Island','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CD','Democratic Republic of the Congo','Kinshasa','CDF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CF','Central African Republic','Bangui','XAF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CG','Republic of the Congo','Brazzaville','XAF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CH','Switzerland','Berne','CHF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CI','Ivory Coast','Yamoussoukro','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CK','Cook Islands','Avarua','NZD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CL','Chile','Santiago','CLP','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CM','Cameroon','Yaounde','XAF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CN','China','Beijing','CNY','Yuan Renminbi');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CO','Colombia','Bogota','COP','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CR','Costa Rica','San Jose','CRC','Colon');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CS','Serbia and Montenegro','Belgrade','RSD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CU','Cuba','Havana','CUP','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CV','Cape Verde','Praia','CVE','Escudo');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CW','Curacao',' Willemstad','ANG','Guilder');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CX','Christmas Island','Flying Fish Cove','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CY','Cyprus','Nicosia','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('CZ','Czech Republic','Prague','CZK','Koruna');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('DE','Germany','Berlin','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('DJ','Djibouti','Djibouti','DJF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('DK','Denmark','Copenhagen','DKK','Krone');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('DM','Dominica','Roseau','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('DO','Dominican Republic','Santo Domingo','DOP','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('DZ','Algeria','Algiers','DZD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('EC','Ecuador','Quito','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('EE','Estonia','Tallinn','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('EG','Egypt','Cairo','EGP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('EH','Western Sahara','El-Aaiun','MAD','Dirham');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ER','Eritrea','Asmara','ERN','Nakfa');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ES','Spain','Madrid','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ET','Ethiopia','Addis Ababa','ETB','Birr');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('FI','Finland','Helsinki','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('FJ','Fiji','Suva','FJD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('FK','Falkland Islands','Stanley','FKP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('FM','Micronesia','Palikir','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('FO','Faroe Islands','Torshavn','DKK','Krone');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('FR','France','Paris','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GA','Gabon','Libreville','XAF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GB','United Kingdom','London','GBP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GD','Grenada','St. George\'s','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GE','Georgia','Tbilisi','GEL','Lari');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GF','French Guiana','Cayenne','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GG','Guernsey','St Peter Port','GBP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GH','Ghana','Accra','GHS','Cedi');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GI','Gibraltar','Gibraltar','GIP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GL','Greenland','Nuuk','DKK','Krone');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GM','Gambia','Banjul','GMD','Dalasi');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GN','Guinea','Conakry','GNF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GP','Guadeloupe','Basse-Terre','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GQ','Equatorial Guinea','Malabo','XAF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GR','Greece','Athens','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GS','South Georgia and the South Sandwich Islands','Grytviken','GBP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GT','Guatemala','Guatemala City','GTQ','Quetzal');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GU','Guam','Hagatna','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GW','Guinea-Bissau','Bissau','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('GY','Guyana','Georgetown','GYD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('HK','Hong Kong','Hong Kong','HKD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('HM','Heard Island and McDonald Islands','','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('HN','Honduras','Tegucigalpa','HNL','Lempira');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('HR','Croatia','Zagreb','HRK','Kuna');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('HT','Haiti','Port-au-Prince','HTG','Gourde');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('HU','Hungary','Budapest','HUF','Forint');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ID','Indonesia','Jakarta','IDR','Rupiah');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IE','Ireland','Dublin','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IL','Israel','Jerusalem','ILS','Shekel');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IM','Isle of Man','Douglas, Isle of Man','GBP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IN','India','New Delhi','INR','Rupee');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IO','British Indian Ocean Territory','Diego Garcia','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IQ','Iraq','Baghdad','IQD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IR','Iran','Tehran','IRR','Rial');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IS','Iceland','Reykjavik','ISK','Krona');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('IT','Italy','Rome','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('JE','Jersey','Saint Helier','GBP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('JM','Jamaica','Kingston','JMD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('JO','Jordan','Amman','JOD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('JP','Japan','Tokyo','JPY','Yen');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KE','Kenya','Nairobi','KES','Shilling');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KG','Kyrgyzstan','Bishkek','KGS','Som');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KH','Cambodia','Phnom Penh','KHR','Riels');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KI','Kiribati','Tarawa','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KM','Comoros','Moroni','KMF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KN','Saint Kitts and Nevis','Basseterre','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KP','North Korea','Pyongyang','KPW','Won');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KR','South Korea','Seoul','KRW','Won');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KW','Kuwait','Kuwait City','KWD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KY','Cayman Islands','George Town','KYD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('KZ','Kazakhstan','Astana','KZT','Tenge');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LA','Laos','Vientiane','LAK','Kip');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LB','Lebanon','Beirut','LBP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LC','Saint Lucia','Castries','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LI','Liechtenstein','Vaduz','CHF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LK','Sri Lanka','Colombo','LKR','Rupee');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LR','Liberia','Monrovia','LRD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LS','Lesotho','Maseru','LSL','Loti');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LT','Lithuania','Vilnius','LTL','Litas');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LU','Luxembourg','Luxembourg','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LV','Latvia','Riga','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('LY','Libya','Tripolis','LYD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MA','Morocco','Rabat','MAD','Dirham');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MC','Monaco','Monaco','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MD','Moldova','Chisinau','MDL','Leu');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ME','Montenegro','Podgorica','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MF','Saint Martin','Marigot','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MG','Madagascar','Antananarivo','MGA','Ariary');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MH','Marshall Islands','Majuro','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MK','Macedonia','Skopje','MKD','Denar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ML','Mali','Bamako','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MM','Myanmar','Nay Pyi Taw','MMK','Kyat');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MN','Mongolia','Ulan Bator','MNT','Tugrik');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MO','Macao','Macao','MOP','Pataca');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MP','Northern Mariana Islands','Saipan','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MQ','Martinique','Fort-de-France','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MR','Mauritania','Nouakchott','MRO','Ouguiya');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MS','Montserrat','Plymouth','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MT','Malta','Valletta','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MU','Mauritius','Port Louis','MUR','Rupee');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MV','Maldives','Male','MVR','Rufiyaa');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MW','Malawi','Lilongwe','MWK','Kwacha');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MX','Mexico','Mexico City','MXN','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MY','Malaysia','Kuala Lumpur','MYR','Ringgit');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('MZ','Mozambique','Maputo','MZN','Metical');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NA','Namibia','Windhoek','NAD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NC','New Caledonia','Noumea','XPF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NE','Niger','Niamey','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NF','Norfolk Island','Kingston','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NG','Nigeria','Abuja','NGN','Naira');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NI','Nicaragua','Managua','NIO','Cordoba');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NL','Netherlands','Amsterdam','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NO','Norway','Oslo','NOK','Krone');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NP','Nepal','Kathmandu','NPR','Rupee');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NR','Nauru','Yaren','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NU','Niue','Alofi','NZD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('NZ','New Zealand','Wellington','NZD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('OM','Oman','Muscat','OMR','Rial');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PA','Panama','Panama City','PAB','Balboa');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PE','Peru','Lima','PEN','Sol');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PF','French Polynesia','Papeete','XPF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PG','Papua New Guinea','Port Moresby','PGK','Kina');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PH','Philippines','Manila','PHP','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PK','Pakistan','Islamabad','PKR','Rupee');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PL','Poland','Warsaw','PLN','Zloty');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PM','Saint Pierre and Miquelon','Saint-Pierre','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PN','Pitcairn','Adamstown','NZD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PR','Puerto Rico','San Juan','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PS','Palestinian Territory','East Jerusalem','ILS','Shekel');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PT','Portugal','Lisbon','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PW','Palau','Melekeok','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('PY','Paraguay','Asuncion','PYG','Guarani');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('QA','Qatar','Doha','QAR','Rial');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('RE','Reunion','Saint-Denis','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('RO','Romania','Bucharest','RON','Leu');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('RS','Serbia','Belgrade','RSD','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('RU','Russia','Moscow','RUB','Ruble');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('RW','Rwanda','Kigali','RWF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SA','Saudi Arabia','Riyadh','SAR','Rial');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SB','Solomon Islands','Honiara','SBD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SC','Seychelles','Victoria','SCR','Rupee');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SD','Sudan','Khartoum','SDG','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SE','Sweden','Stockholm','SEK','Krona');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SG','Singapore','Singapur','SGD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SH','Saint Helena','Jamestown','SHP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SI','Slovenia','Ljubljana','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SJ','Svalbard and Jan Mayen','Longyearbyen','NOK','Krone');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SK','Slovakia','Bratislava','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SL','Sierra Leone','Freetown','SLL','Leone');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SM','San Marino','San Marino','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SN','Senegal','Dakar','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SO','Somalia','Mogadishu','SOS','Shilling');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SR','Suriname','Paramaribo','SRD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SS','South Sudan','Juba','SSP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ST','Sao Tome and Principe','Sao Tome','STD','Dobra');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SV','El Salvador','San Salvador','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SX','Sint Maarten','Philipsburg','ANG','Guilder');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SY','Syria','Damascus','SYP','Pound');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('SZ','Swaziland','Mbabane','SZL','Lilangeni');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TC','Turks and Caicos Islands','Cockburn Town','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TD','Chad','N\'Djamena','XAF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TF','French Southern Territories','Port-aux-Francais','EUR','Euro  ');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TG','Togo','Lome','XOF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TH','Thailand','Bangkok','THB','Baht');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TJ','Tajikistan','Dushanbe','TJS','Somoni');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TK','Tokelau','','NZD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TL','East Timor','Dili','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TM','Turkmenistan','Ashgabat','TMT','Manat');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TN','Tunisia','Tunis','TND','Dinar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TO','Tonga','Nuku\'alofa','TOP','Pa\'anga');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TR','Turkey','Ankara','TRY','Lira');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TT','Trinidad and Tobago','Port of Spain','TTD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TV','Tuvalu','Funafuti','AUD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TW','Taiwan','Taipei','TWD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('TZ','Tanzania','Dodoma','TZS','Shilling');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('UA','Ukraine','Kiev','UAH','Hryvnia');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('UG','Uganda','Kampala','UGX','Shilling');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('UM','United States Minor Outlying Islands','','USD','Dollar ');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('US','United States','Washington','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('UY','Uruguay','Montevideo','UYU','Peso');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('UZ','Uzbekistan','Tashkent','UZS','Som');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('VA','Vatican','Vatican City','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('VC','Saint Vincent and the Grenadines','Kingstown','XCD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('VE','Venezuela','Caracas','VEF','Bolivar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('VG','British Virgin Islands','Road Town','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('VI','U.S. Virgin Islands','Charlotte Amalie','USD','Dollar');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('VN','Vietnam','Hanoi','VND','Dong');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('VU','Vanuatu','Port Vila','VUV','Vatu');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('WF','Wallis and Futuna','Mata Utu','XPF','Franc');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('WS','Samoa','Apia','WST','Tala');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('XK','Kosovo','Pristina','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('YE','Yemen','Sanaa','YER','Rial');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('YT','Mayotte','Mamoudzou','EUR','Euro');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ZA','South Africa','Pretoria','ZAR','Rand');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ZM','Zambia','Lusaka','ZMK','Kwacha');
INSERT INTO `` (`iso`,`country`,`capital`,`currency_code`,`currency_name`) VALUES ('ZW','Zimbabwe','Harare','ZWL','Dollar');
